@startwbs

scale max 700 width

+[#DeepSkyBlue] C++学習ロードマップ
++[#SkyBlue] シンタックス学習(3ヶ月)
+++[#Pink] ストラウストラップ本\n(1H/day)
+++[#Pink] 質疑応答\n(1H/W)
++[#SkyBlue]  C++コーディングルール(2ヶ月)
+++[#Pink] ルールセミナー\n(2H/2W, 全8回)
++[#SkyBlue] OOD設計セミナー(3ヶ月)
+++[#Pink] SOLIDセミナー\n(2H/2W, 全2回)
+++[#Pink] デザインパターンセミナー\n(2H/2W, 全8回)
++[#SkyBlue] 開発環境立ち上げ(3ヶ月)
+++[#Pink] リファクター\nレガシー C →  C++/OOD
+++[#Pink] google test &\nmake環境立ち上げ
+++[#Pink] CI/静的解析立ち上げ
@endwbs

